version: "2"
services:
  db:
    build:
      context: ../db
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    ports:
      - "80:3000"
    links:
      - db
    environment:
      - DB_HOST=mongodb://db:27017/posts